### ISSUE TITLE
How to changes the tf code?

### ISSUE THREAD

**Issue by LinkZyy** [zhaohb/tensorflow_fpga_distributed#1]
Hello, I want to run this scripts on my FPGA. How ever it seems like I have to change the tensorflow source code.  What should I do?

By the way, what version of tensorflow are you using? Sincerely look forward to your reply？

Thank you very much

**Comment by LinkZyy** [comment]
If it is convenient for you, can you provide the code of tensorflow that supports FPGA？

**Comment by zhaohb** [comment]
@LinkZyy maybe you should supprt fpga device in tf, and you must add op for fpga device, I am using tf1.6

**Comment by zhaohb** [comment]
I can not give you the code, but i can tell you how to add device, and how to write the op of fpga, and so on.

**Comment by LinkZyy** [comment]
Thank you for your reply！！ I'll try it myself first

**Comment by zhaohb** [comment]
you are welcome,  good luck
